---
language: ruby

rvm:
  - 2.5.1
  - 2.6.5

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_edge.gemfile

script:
  - rubocop && bundle exec rake test
